Move note creation logic ton one file and reuse it for `ideas`, `wiki` & `note`

diff --git a/note b/note
--- a/note
+++ b/note
@@ -1,89 +1,33 @@
 #!/bin/bash
 
-required_date="${1:-today}"
+INITIAL_LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
-initialLocation="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-rootFolder="$( cat "${initialLocation}/.noteFolderPath")"
+print_usage () {
+    echo "Usage:"
+    echo "$PWD/$(basename $0) [category [sub-category]] name"
+}
 
-action='note'
-if [[ $1 == '--list' ||  $1 == '-l' ]]; then
-    action='list'
-    shift
-
-    # Gather arguments
-    if [[ $# == 2 ]]; then
-        category="$1/"
-        shift
-    fi
-
-    if [[ $# == 1 ]]; then
-        sub_category="$1/"
-        shift
-    fi
-
-    pushd ${rootFolder}/notes
-    file_path="${category}${sub_category}"
-
-    tree -d $file_path
-    popd
-    exit 0
+# Process arguments
+if [[ $# == 0 ]]; then
+    echo "Can't create a note without name"
+    echo ""
+    print_usage
+    exit 1
 fi
 
-# Gather arguments
 if [[ $# == 3 ]]; then
-    category="/$1"
+    category="$1"
     shift
 fi
 
 if [[ $# == 2 ]]; then
-    sub_category="/$1"
+    sub_category="$1"
     shift
 fi
 
 if [[ $# == 1 ]]; then
     note_name="$1"
-    file_name="/$note_name.md"
     shift
 fi
 
-file_path="${rootFolder}/notes${category}${sub_category}${file_name}"
-
-mkdir -p $(dirname $file_path)
-
-
-# Create new file if it doesn't exist
-is_new_file=0
-if [[ ! -f $file_path ]]; then
-    is_new_file=1
-    echo "$note_name" >> "$file_path"
-    echo "===" >> "$file_path"
-    echo "> Created '$(date)' by $(whoami)" >> "$file_path"
-fi
-
-
-# Stage the file to git so we can see if it changed once the user is done editing
-pushd $rootFolder
-    git add "$file_path"
-
-    # Edit the file
-    echo "Editing file ${file_path}"
-    ${EDITOR} "$file_path"
-
-    if [[ ! -z "$(git diff "$file_path")" ]]; then
-        # The file was changed, commit it to git
-        pushd $rootFolder
-            git add "$file_path"
-            git commit "$file_path"
-            git push origin
-        popd
-    else
-        # File wasn't changed, either cleanup or exit
-        if [[ $is_new_file == 1 ]]; then
-            echo "Removing file '$file_path' as it was left unchanged from its default template"
-            rm -f "$file_path"
-            git add "$file_path"
-        else
-            echo "No change detected for file '$file_path'"
-        fi
-    fi
-popd
+$INITIAL_LOCATION/scripts/quick-note.sh 'note' "${category}" "${sub_category}" "${note_name}"
